export const INITIALIZE = 'INITIALIZE';

export const UPDATE_CORE_INFO = 'UPDATE_CORE_INFO';
export const UPDATE_THEME = 'UPDATE_THEME';
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS';

export const SHOW_CONNECTIONS = 'SHOW_CONNECTIONS';
export const HIDE_CONNECTIONS = 'HIDE_CONNECTIONS';

export const UPDATE_INPUT = 'UPDATE_INPUT';

export const IS_BEST_RATE = 'IS_BEST_RATE';
export const IS_LOADING = 'IS_LOADING';
export const UPDATE_FROM_AMOUNT = 'UPDATE_FROM_AMOUNT';
export const UPDATE_TO_AMOUNT = 'UPDATE_TO_AMOUNT';
export const UPDATE_FROM_ACCOUNT = 'UPDATE_FROM_ACCOUNT';
export const UPDATE_TO_ADDRESS = 'UPDATE_TO_ADDRESS';
export const UPDATE_ACCOUNTS = 'UPDATE_ACCOUNTS';
export const UPDATE_COINS = 'UPDATE_COINS';
export const UPDATE_TO_COIN = 'UPDATE_TO_COIN';
export const UPDATE_RATE = 'UPDATE_RATE';
export const UPDATE_PARTNERS = 'UPDATE_PARTNERS';
export const SAVE_TRANSACTION = 'SAVE_TRANSACTION';
export const UPDATE_QUOTA_ID = 'UPDATE_QUOTA_ID';
